In [123]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt


In [124]:
X=np.loadtxt(r"C:\Users\muham\Downloads\ML algorithrme\ex2x.dat")

In [125]:
X

array([2.0658746, 2.3684087, 2.5399929, 2.5420804, 2.549079 , 2.7866882,
       2.9116825, 3.035627 , 3.1146696, 3.1582389, 3.3275944, 3.3793165,
       3.4122006, 3.4215823, 3.5315732, 3.6393002, 3.6732537, 3.9256462,
       4.0498646, 4.2483348, 4.3440052, 4.3826531, 4.4230602, 4.6102443,
       4.6881183, 4.9777333, 5.0359967, 5.0684536, 5.4161491, 5.4395623,
       5.4563207, 5.5698458, 5.6015729, 5.6877617, 5.7215602, 5.8538914,
       6.1978026, 6.3510941, 6.4797033, 6.7383791, 6.8637686, 7.0223387,
       7.0782373, 7.1514232, 7.4664023, 7.5973874, 7.7440717, 7.7729662,
       7.8264514, 7.9306356])

In [126]:
Y=np.loadtxt(r"C:\Users\muham\Downloads\ML algorithrme\ex2y.dat")

In [127]:
Y

array([0.77918926, 0.91596757, 0.90538354, 0.90566138, 0.9389889 ,
       0.9668474 , 0.96436824, 0.91445939, 0.93933944, 0.96074971,
       0.89837094, 0.91209739, 0.94238499, 0.96624578, 1.05265   ,
       1.0143791 , 0.95969426, 0.96853716, 1.0766065 , 1.1454978 ,
       1.0340625 , 1.0070009 , 0.96683648, 1.0895919 , 1.0634462 ,
       1.1237239 , 1.0323374 , 1.0874452 , 1.0702988 , 1.1606493 ,
       1.0778037 , 1.1069758 , 1.0971875 , 1.1648603 , 1.1411796 ,
       1.0844156 , 1.1252493 , 1.1168341 , 1.1970789 , 1.2069462 ,
       1.1251046 , 1.1235672 , 1.2132829 , 1.2522652 , 1.2497065 ,
       1.1799706 , 1.1897299 , 1.3029934 , 1.2601134 , 1.2562267 ])

In [128]:
X.shape

(50,)

In [129]:
Y.shape

(50,)

In [130]:
### now to perform the vectorize opration we want to make the column of 1 
ones=np.ones([X.shape[0],1])
#
ones.shape


(50, 1)

In [131]:
X=X.reshape(X.shape[0],1)


#
X.shape

(50, 1)

In [132]:
X=np.concat((ones,X),axis=1)

In [133]:
X

array([[1.       , 2.0658746],
       [1.       , 2.3684087],
       [1.       , 2.5399929],
       [1.       , 2.5420804],
       [1.       , 2.549079 ],
       [1.       , 2.7866882],
       [1.       , 2.9116825],
       [1.       , 3.035627 ],
       [1.       , 3.1146696],
       [1.       , 3.1582389],
       [1.       , 3.3275944],
       [1.       , 3.3793165],
       [1.       , 3.4122006],
       [1.       , 3.4215823],
       [1.       , 3.5315732],
       [1.       , 3.6393002],
       [1.       , 3.6732537],
       [1.       , 3.9256462],
       [1.       , 4.0498646],
       [1.       , 4.2483348],
       [1.       , 4.3440052],
       [1.       , 4.3826531],
       [1.       , 4.4230602],
       [1.       , 4.6102443],
       [1.       , 4.6881183],
       [1.       , 4.9777333],
       [1.       , 5.0359967],
       [1.       , 5.0684536],
       [1.       , 5.4161491],
       [1.       , 5.4395623],
       [1.       , 5.4563207],
       [1.       , 5.5698458],
       [

In [134]:
## define the hypotesis
def Hypothesis(theta,X):
    return np.dot(theta,X)


In [135]:
### define the cost function
def cost(Y,y_pred):
    m=len(Y)
    error=y_pred-Y
    return (1/(2*m))* np.sum(error**2)
#Gradient Descent
def gradient_descent(X, Y, theta, alpha, iterations):

    m = len(Y)

    for i in range(iterations):

        # Prediction
        y_pred = Hypothesis(X, theta)

        # Error
        error = y_pred - Y

        # Gradient
        gradient = (1 / m) * np.dot(X.T, error)

        # Update theta
        theta = theta - alpha * gradient

        # Print Cost
        if i % 100 == 0:
            print(f"Iteration {i}  Cost = {cost(Y, y_pred)}")

    return theta


In [136]:
# Initial theta
theta = np.zeros(2)

# Hyperparameters
alpha = 0.1
iterations = 1000

# Training
theta = gradient_descent(X, Y, theta, alpha, iterations)

print("Theta =", theta)
#Prediction
y_pred = Hypothesis(X, theta)
print(y_pred)



Iteration 0  Cost = 0.5737324907367211
Iteration 100  Cost = 1.227892283436311e+51
Iteration 200  Cost = 2.765271144476219e+102
Iteration 300  Cost = 6.227520610417978e+153
Iteration 400  Cost = 1.402466916513784e+205
Iteration 500  Cost = 3.158421424772545e+256
Iteration 600  Cost = inf
Iteration 700  Cost = inf
Iteration 800  Cost = inf
Iteration 900  Cost = inf
Theta = [-2.04402511e+255 -1.12347615e+256]
[-2.52536335e+256 -2.86525319e+256 -3.05802395e+256 -3.06036920e+256
 -3.06823196e+256 -3.33518023e+256 -3.47560835e+256 -3.61485704e+256
 -3.70365951e+256 -3.75260858e+256 -3.94287544e+256 -4.00098399e+256
 -4.03792849e+256 -4.04846861e+256 -4.17204076e+256 -4.29306948e+256
 -4.33121542e+256 -4.61477238e+256 -4.75432879e+256 -4.97730532e+256
 -5.08478873e+256 -5.12820873e+256 -5.17360514e+256 -5.38390201e+256
 -5.47139159e+256 -5.79676714e+256 -5.86222468e+256 -5.89868923e+256
 -6.28931683e+256 -6.31562100e+256 -6.33444867e+256 -6.46199141e+256
 -6.49763605e+256 -6.59446711e+256 -6

C:\Users\muham\AppData\Local\Temp\ipykernel_9744\868140401.py:5: RuntimeWarning: overflow encountered in square
  return (1/(2*m))* np.sum(error**2)
c:\Users\muham\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\_core\fromnumeric.py:83: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


In [137]:
l=[]
epochs=[]
for epoch in range(iterations):
    epochs.append(epoch)
    y_pred=Hypothesis(theta,X)
    los=cost(Y,y_pred)
    l.append(los)
    dw=gradient_descent(X,Y,y_pred)
    

ValueError: shapes (2,) and (50,2) not aligned: 2 (dim 0) != 50 (dim 0)