In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt


In [2]:
X=np.loadtxt('C:\\Users\\muham\\Downloads\\ex2x.dat')
Y=np.loadtxt('C:\\Users\\muham\\Downloads\\ex2y.dat')
X

array([2.0658746, 2.3684087, 2.5399929, 2.5420804, 2.549079 , 2.7866882,
       2.9116825, 3.035627 , 3.1146696, 3.1582389, 3.3275944, 3.3793165,
       3.4122006, 3.4215823, 3.5315732, 3.6393002, 3.6732537, 3.9256462,
       4.0498646, 4.2483348, 4.3440052, 4.3826531, 4.4230602, 4.6102443,
       4.6881183, 4.9777333, 5.0359967, 5.0684536, 5.4161491, 5.4395623,
       5.4563207, 5.5698458, 5.6015729, 5.6877617, 5.7215602, 5.8538914,
       6.1978026, 6.3510941, 6.4797033, 6.7383791, 6.8637686, 7.0223387,
       7.0782373, 7.1514232, 7.4664023, 7.5973874, 7.7440717, 7.7729662,
       7.8264514, 7.9306356])

In [3]:
Y

array([0.77918926, 0.91596757, 0.90538354, 0.90566138, 0.9389889 ,
       0.9668474 , 0.96436824, 0.91445939, 0.93933944, 0.96074971,
       0.89837094, 0.91209739, 0.94238499, 0.96624578, 1.05265   ,
       1.0143791 , 0.95969426, 0.96853716, 1.0766065 , 1.1454978 ,
       1.0340625 , 1.0070009 , 0.96683648, 1.0895919 , 1.0634462 ,
       1.1237239 , 1.0323374 , 1.0874452 , 1.0702988 , 1.1606493 ,
       1.0778037 , 1.1069758 , 1.0971875 , 1.1648603 , 1.1411796 ,
       1.0844156 , 1.1252493 , 1.1168341 , 1.1970789 , 1.2069462 ,
       1.1251046 , 1.1235672 , 1.2132829 , 1.2522652 , 1.2497065 ,
       1.1799706 , 1.1897299 , 1.3029934 , 1.2601134 , 1.2562267 ])

In [4]:
X.shape

(50,)

In [5]:
Y.shape

(50,)

## convert into 2 diamensial 

In [6]:
one=np.ones([X.shape[0],1])
one
X=X.reshape([X.shape[0],1])
X.shape


(50, 1)

In [7]:
X=np.concatenate((one,X),axis=1) # axise one means the column
X

array([[1.       , 2.0658746],
       [1.       , 2.3684087],
       [1.       , 2.5399929],
       [1.       , 2.5420804],
       [1.       , 2.549079 ],
       [1.       , 2.7866882],
       [1.       , 2.9116825],
       [1.       , 3.035627 ],
       [1.       , 3.1146696],
       [1.       , 3.1582389],
       [1.       , 3.3275944],
       [1.       , 3.3793165],
       [1.       , 3.4122006],
       [1.       , 3.4215823],
       [1.       , 3.5315732],
       [1.       , 3.6393002],
       [1.       , 3.6732537],
       [1.       , 3.9256462],
       [1.       , 4.0498646],
       [1.       , 4.2483348],
       [1.       , 4.3440052],
       [1.       , 4.3826531],
       [1.       , 4.4230602],
       [1.       , 4.6102443],
       [1.       , 4.6881183],
       [1.       , 4.9777333],
       [1.       , 5.0359967],
       [1.       , 5.0684536],
       [1.       , 5.4161491],
       [1.       , 5.4395623],
       [1.       , 5.4563207],
       [1.       , 5.5698458],
       [

## hypotesis

In [8]:
def hypotesis(W,x):
    return np.dot(x,W)

In [9]:
f=hypotesis(X.T)

TypeError: hypotesis() missing 1 required positional argument: 'x'

In [ ]:
def cost(m,y,y_predicted):
    return((1/(2*m))*np.sum(np.square(y_predicted-y)))

In [ ]:
def gradient(m,x,y,y_predicted):
    return((1/m)*np.dot(x.T,y_predicted-y))

In [ ]:
gradient(m,X,Y,f)

NameError: name 'm' is not defined